import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Course from "../../layouts/Course";

const Cluster = ({ cluster }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>{cluster.title} | CLUSTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-2/4 flex justify-center items-center">
        <h1 className="text-7xl">
          Welcome to {`\n`} {cluster.title} cluster
        </h1>
      </div>
    </>
  );
};

export const getStaticProps = async ({ params }) => {
  const res = await fetch(`http://localhost:1337/clusters/${params.cluster}`);
  const data = await res.json();
  return {
    props: { cluster: data },
  };
};

export const getStaticPaths = async () => {
  const res = await fetch("http://localhost:1337/clusters");
  const data = await res.json();
  const paths = data.map((cluster) => {
    return {
      params: { cluster: cluster.slug },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

Cluster.PageLayout = Course;

export default Cluster;
