import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";
import Head from "next/head";
import Link from "next/link";
import { useTheme } from "next-themes";

const ThemeChanger = () => {
  const [mounted, setMounted] = useState(false);
  const { setTheme } = useTheme();
  // When mounted on client, now we can show the UI
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return (
    <div className="absolute top-8 right-8">
      <button
        type="button"
        className="rounded-full m-4 w-12 h-12 "
        onClick={() => setTheme("light")}
      >
        L
      </button>
      <button
        type="button"
        className="rounded-full m-4 w-12 h-12"
        onClick={() => setTheme("dark")}
      >
        D
      </button>
    </div>
  );
};

export default function Home({ superclusters }) {
  return (
    <div className="dark:bg-black min-h-screen">
      <Head>
        <title>CLUSTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-blue-700 text-center text-6xl uppercase pt-8 font-bold">
        Cluster🌌
      </h1>
      {ThemeChanger()}
      <div className="px-8">
        <h1 className="text-6xl mb-8">Links</h1>
        <ul>
          {superclusters.map((supercluster) => (
            <Link href={`/${supercluster.slug}`} key={supercluster.id} passHref>
              <li className="text-3xl py-2 cursor-pointer hover:translate-x-2">
                {supercluster.title}
              </li>
            </Link>
          ))}
        </ul>
      </div>
    </div>
  );
}

Home.propTypes = {
  superclusters: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string,
    })
  ),
};

Home.defaultProps = {
  superclusters: [],
};

export const getStaticProps = async () => {
  const res = await fetch("https://clustercms.herokuapp.com/superclusters");
  const superclusters = await res.json();
  return {
    props: { superclusters },
  };
};
